name: 'vmtest'
description: 'Build + run vmtest'
inputs:
  kernel:
    description: 'kernel version or LATEST'
    required: true
    default: 'LATEST'
  arch:
    description: 'what arch to test'
    required: true
    default: 'x86_64'
  pahole:
    description: 'pahole rev or master'
    required: true
    default: 'master'
  llvm-version:
    description: 'llvm version'
    required: false
    default: '17'
runs:
  using: "composite"
  steps:
    # setup environment
    - name: Setup environment
      uses: libbpf/ci/setup-build-env@main
      with:
        pahole: ${{ inputs.pahole }}
        arch: ${{ inputs.arch }}
        llvm-version: ${{ inputs.llvm-version }}
    # 1. download CHECKPOINT kernel source
    - name: Get checkpoint commit
      shell: bash
      run: |
        cat CHECKPOINT-COMMIT
        echo "CHECKPOINT=$(cat CHECKPOINT-COMMIT)" >> $GITHUB_ENV
    - name: Get kernel source at checkpoint
      uses: libbpf/ci/get-linux-source@main
      with:
        repo: 'https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git'
        rev: ${{ env.CHECKPOINT }}
        dest: '${{ github.workspace }}/.kernel'
    - name: Move linux source in place
      shell: bash
      run: |
        rm -rf .kernel/.git
        cp -rf .kernel/. .
        rm -rf .kernel
    - uses: libbpf/ci/patch-kernel@main
      with:
        patches-root: '${{ github.workspace }}/ci/diffs'
        repo-root: '${{ github.workspace }}'
    # 2. if kernel == LATEST, build kernel image from tree
    - name: Build kernel image
      if: ${{ inputs.kernel == 'LATEST' }}
      uses: libbpf/ci/build-linux@main
      with:
        arch: ${{ inputs.arch }}
        toolchain: ${{ inputs.toolchain }}
        kbuild-output: ${{ env.KBUILD_OUTPUT }}
        max-make-jobs: 32
        llvm-version: ${{ inputs.llvm-version }}
    # else, just download prebuilt kernel image
    - name: Download prebuilt kernel
      if: ${{ inputs.kernel != 'LATEST' }}
      uses: libbpf/ci/download-vmlinux@main
      with:
        kernel: ${{ inputs.kernel }}
        arch: ${{ inputs.arch }}
    # 3. build selftests
    - name: Prepare to build BPF selftests
      if: ${{ inputs.kernel != 'LATEST' }}
      shell: bash
      run: |
        source $GITHUB_ACTION_PATH/../../../ci/vmtest/helpers.sh
        foldable start "Prepare building selftest"
        cat tools/testing/selftests/bpf/config \
            tools/testing/selftests/bpf/config.${{ inputs.arch }} > .config
        # this file might or mihgt not exist depending on kernel version
        cat tools/testing/selftests/bpf/config.vm >> .config || :
        make olddefconfig && make prepare
        foldable end
    - name: Build selftests
      uses: libbpf/ci/build-selftests@main
      with:
        arch: ${{ inputs.arch }}
        toolchain: ${{ inputs.toolchain }}
        kbuild-output: ${{ env.KBUILD_OUTPUT }}
        max-make-jobs: 32
        llvm-version: ${{ inputs.llvm-version }}
    # 4. run selftest in vmtest
    - name: Run selftests
      env:
        KERNEL: ${{ inputs.kernel }}
        REPO_ROOT: ${{ github.workspace }}
      uses: libbpf/ci/run-vmtest@main
      with:
        arch: ${{ inputs.arch }}
        vmlinuz: '${{ github.workspace }}/.kernel/vmlinuz'
        kernel-root: '.'
